;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Input.Burst.1",DevComment="")
+GameplayTagList=(Tag="MG.Ability.Attack.Combo.Left1",DevComment="")
+GameplayTagList=(Tag="MG.Ability.Attack.Combo.Left2",DevComment="")
+GameplayTagList=(Tag="MG.Ability.Parry",DevComment="")
+GameplayTagList=(Tag="MG.Input.Attack.Left.Hold",DevComment="")
+GameplayTagList=(Tag="MG.Input.Attack.Right.Hold",DevComment="")

