[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=04E62B334FBF39975986AC89A827AFCA
ProjectName=Third Person Game Template

[/Script/MG.MGAssetManager]
; DA_MGGameData 에셋을 생성한 뒤 아래 경로를 실제 경로로 변경하세요.
GameDataPath=/Game/System/DataAsset/DA_MGGameData.DA_MGGameData

[/Script/Engine.AssetManagerSettings]
; MGGameData primary asset type
+PrimaryAssetTypesToScan=(PrimaryAssetType="MGGameData",AssetBaseClass=/Script/MG.MGGameData,bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=((Path="/Game/System/DataAsset")),SpecificAssets=(),Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=AlwaysCook,bPatchUsingSecondaryChunkId=False))
; MGPawnData primary asset type
+PrimaryAssetTypesToScan=(PrimaryAssetType="MGPawnData",AssetBaseClass=/Script/MG.MGPawnData,bHasBlueprintClasses=False,bIsEditorOnly=False,Directories=((Path="/Game/System/DataAsset")),SpecificAssets=(),Rules=(Priority=-1,ChunkId=-1,bApplyRecursively=True,CookRule=AlwaysCook,bPatchUsingSecondaryChunkId=False))
